data:
  img_size: 640
  pad: 0.5
  #path: /home/agc2021/dataset
  path: coco/images/val2017
  rect: true
  use_mp: false
inference:
  agnostic: true
  batch_size: 8
  conf_t: 0.000338306851470947
  iou_t: 0.561842277678083
  nms_box: 1000
model:
  half: false
  n_param: 86705005
  name: yolov5x
  stride_size: 32
  wandb: j-marple/AYolov2/1gxaqgk4
  weights: model.pt
