model:
  name: yolov5l_decomposed
  weights: weights/model.pt
  stride_size: 32
  n_param: 27450291
  wandb: j-marple/AYolov2/xz6qgknu
  half: False

inference:
  batch_size: 8
  conf_t: 0.001
  iou_t: 0.65
  nms_box: 500
  agnostic: False 

data:
  # path: /home/agc2021/dataset
  path: /home/user/coco/images/val2017
  img_size: 640
  rect: True
  use_mp: False
  pad: 0.5
  
